export const notifications = [
  { type: "deposit", name: "Caleb", country: "Denmark", amount: "$4100" },
  { type: "earning", name: "Elijah", country: "Finland", amount: "$529" },
  { type: "withdrawal", name: "Julian", country: "Chile", amount: "$7640" },
  { type: "deposit", name: "Lily", country: "Colombia", amount: "$2600" },
  { type: "earning", name: "Mila", country: "Germany", amount: "$586" },
  { type: "withdrawal", name: "Nathan", country: "Canada", amount: "$9990" },
  { type: "earning", name: "Isla", country: "Norway", amount: "$785" },
  { type: "deposit", name: "Zara", country: "Sweden", amount: "$2200" },
  { type: "withdrawal", name: "Ariana", country: "France", amount: "$4100" },
  { type: "deposit", name: "Lea", country: "Mexico", amount: "$1200" },
  { type: "earning", name: "Zoe", country: "Belgium", amount: "$301" },
  { type: "withdrawal", name: "Gabriel", country: "Austria", amount: "$7820" },
  { type: "earning", name: "Emma", country: "France", amount: "$301" },
  { type: "deposit", name: "Carter", country: "Canada", amount: "$3900" },
  { type: "earning", name: "Lucas", country: "Brazil", amount: "$427" },
  { type: "withdrawal", name: "Mira", country: "Peru", amount: "$5600" },
  { type: "earning", name: "Aria", country: "Netherlands", amount: "$271" },
  { type: "withdrawal", name: "Nora", country: "Germany", amount: "$6350" },
  { type: "deposit", name: "Eva", country: "Japan", amount: "$800" },
  { type: "earning", name: "Ava", country: "Argentina", amount: "$250" },
  { type: "withdrawal", name: "Levi", country: "Portugal", amount: "$8300" },
  { type: "earning", name: "Leo", country: "Austria", amount: "$390" },
  { type: "deposit", name: "Sebastian", country: "Ecuador", amount: "$3600" },
  { type: "withdrawal", name: "Freya", country: "Norway", amount: "$9040" },
  { type: "deposit", name: "Owen", country: "Chile", amount: "$1800" },
  { type: "withdrawal", name: "Ezra", country: "Mexico", amount: "$7200" },
  { type: "earning", name: "Ethan", country: "Australia", amount: "$366" },
  { type: "deposit", name: "Mateo", country: "Hungary", amount: "$2900" },
  { type: "withdrawal", name: "Lina", country: "Colombia", amount: "$6710" },
  { type: "deposit", name: "Dylan", country: "Norway", amount: "$5000" },
  { type: "earning", name: "Noah", country: "Italy", amount: "$404" },
  { type: "withdrawal", name: "Hudson", country: "Greece", amount: "$6150" },
  { type: "earning", name: "Liam", country: "Mexico", amount: "$777" },
  { type: "deposit", name: "Ivy", country: "Argentina", amount: "$950" },
  { type: "withdrawal", name: "Isaac", country: "Japan", amount: "$8900" },
  { type: "earning", name: "Chloe", country: "Ireland", amount: "$312" },
  { type: "deposit", name: "Logan", country: "Poland", amount: "$1900" },
  { type: "withdrawal", name: "Jayden", country: "Italy", amount: "$9900" },
  { type: "earning", name: "Ella", country: "Sweden", amount: "$458" },
  { type: "deposit", name: "Sara", country: "Austria", amount: "$1100" },
  { type: "withdrawal", name: "Lara", country: "Brazil", amount: "$5200" },
  { type: "earning", name: "Grace", country: "Portugal", amount: "$340" },
  { type: "deposit", name: "Daniel", country: "Germany", amount: "$1800" },
  { type: "withdrawal", name: "Stella", country: "Argentina", amount: "$8730" },
  { type: "earning", name: "Benjamin", country: "Switzerland", amount: "$478" },
  { type: "deposit", name: "Maya", country: "Peru", amount: "$900" },
  { type: "withdrawal", name: "Henry", country: "Spain", amount: "$8450" },
  { type: "earning", name: "James", country: "Chile", amount: "$234" },
  { type: "deposit", name: "Anna", country: "Greece", amount: "$3100" },
  { type: "withdrawal", name: "Clara", country: "Poland", amount: "$5040" },
  { type: "earning", name: "Oliver", country: "Canada", amount: "$721" },
  { type: "deposit", name: "Jackson", country: "Belgium", amount: "$5200" },
  { type: "withdrawal", name: "Elise", country: "Denmark", amount: "$4780" },
  { type: "earning", name: "Sofia", country: "Spain", amount: "$633" },
  { type: "deposit", name: "Nina", country: "Romania", amount: "$1250" },
  {
    type: "withdrawal",
    name: "Sienna",
    country: "Switzerland",
    amount: "$7200",
  },
  { type: "earning", name: "Mason", country: "Japan", amount: "$622" },
  { type: "deposit", name: "Luna", country: "Italy", amount: "$2450" },
  { type: "withdrawal", name: "Grayson", country: "Ecuador", amount: "$9400" },
  { type: "earning", name: "Sophia", country: "Netherlands", amount: "$271" },
  { type: "deposit", name: "Aiden", country: "France", amount: "$3200" },
];
